### ISSUE TITLE
Checking results without scratch cards

### ISSUE THREAD

**Issue by toliano** [ekumahost/my-complete-high-school-portal#14]
Greetings,

Please how can I disable the use of scratch cards for student to be able to check their result? Since the scratch cards generated can't be used to credit the student portal.

Many Thanks in advance

**Comment by kelvin019** [comment]
NB: The scratch card generated can be used to credit the student wallet.
What errors are you having and can you give us access or screenshots when you are trying to credit the wallet?
We have tested the portal across all PHP versions and its working fine.

To remove the scratch card feature, you will have to edit the file:
student/dashboard/results/result_wallet_processing.php

You can drop your emails address so that we can send you the updated version if you do not want to use the scratch card feature for result checking.

You will have to replace the file we will be sending with "student/dashboard/results/result_wallet_processing.php"

**Comment by toliano** [comment]
Thanks for your response sir 🙏🙏. I keep getting this error message [image here](https://imgur.com/NdoRaEG) whenever I'm using the scratch card to credit the students wallet. Here is my email address sir🙏 onitemmy2@gmail.com

Many Thanks 🙏

**Comment by kelvin019** [comment]
Hello,

Are you a developer?
Can you check if the table:

"student_wallet"

is in your database table?

**Comment by toliano** [comment]
Just an upcoming developer sir. 
Yes, I have the STUDENT_WALLET table in my database

**Comment by toliano** [comment]
Hello sir, when is it likely for a new update to be released?

**Comment by kelvin019** [comment]
Hello Toliano,

We have contacted you via email.
Replace the "student/dashboard/results/" with the one sent to you.

We hope this fixes your issue

**Comment by toliano** [comment]
Good day sir. I'm sorry I haven't receive the mail 🙏 onitemmy2@gmail.com

**Comment by toliano** [comment]
Thanks a million sir 🙏 it works like magic
